package com.hippocampus.rag.domain;

public enum EvidenceLimitationCode {
    INSUFFICIENT_EVIDENCE,
    RETRIEVAL_FAILED,
    CHUNK_BUDGET_APPLIED,
    VISUAL_BUDGET_APPLIED,
    LIMITED_CHUNK_SOURCE_QUALITY,
    POOR_CHUNK_SOURCE_QUALITY,
    LIMITED_VISUAL_INTERPRETATION,
    VISUAL_EXCLUDED_BY_INTERPRETATION_STATUS
}
