package com.hippocampus.ai.application.validation;

public enum ResponseEvaluationAggregationFailureReason {
    INCOMPLETE_COVERAGE,
    DUPLICATE_CONCEPT_INDEX,
    OUT_OF_RANGE_CONCEPT_INDEX,
    INVALID_SUPPORTED_SHAPE,
    INVALID_PARTIAL_SHAPE,
    MISSING_WITH_SUPPORTED_COMPONENTS,
    MISSING_WITH_DEMONSTRATED_MISCONCEPTION,
    MISSING_WITH_BLANK_STUDENT_CLAIM,
    MISSING_WITH_BLANK_SUPPORTED_COMPONENT,
    MISSING_WITH_BLANK_MISSING_COMPONENT,
    MISSING_WITH_BLANK_MISCONCEPTION,
    INVALID_CONTRADICTED_SHAPE,
    INVALID_ASSESSABILITY_SHAPE
}
