package com.hippocampus.materials.infrastructure.persistence;

import java.sql.Timestamp; import java.time.Instant; import java.util.List; import java.util.Objects; import java.util.UUID;
import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.transaction.support.TransactionSynchronizationManager;
import tools.jackson.core.JacksonException; import tools.jackson.databind.ObjectMapper;
import com.hippocampus.materials.domain.*; import com.hippocampus.materials.port.*;

public final class JdbcChunkRepository implements ChunkingSourceRepository,ChunkPersistence {
 private static final String ELIGIBLE="""
SELECT mv.page_count FROM material_versions mv JOIN materials m ON m.id=mv.material_id WHERE mv.id=:version AND m.status<>'DELETED' AND m.material_type='PDF' AND m.mime_type='application/pdf' AND mv.storage_key IS NOT NULL AND btrim(mv.storage_key)<>'' AND mv.file_size_bytes>0 AND mv.page_count>0
""";
 private final JdbcClient jdbc;private final ObjectMapper json;
 public JdbcChunkRepository(JdbcClient jdbc,ObjectMapper json){this.jdbc=Objects.requireNonNull(jdbc);this.json=Objects.requireNonNull(json);}
 @Override public int requirePageCount(UUID v){return jdbc.sql(ELIGIBLE).param("version",v).query(Integer.class).optional().orElseThrow(()->new IllegalStateException("Material version is not eligible for chunking"));}
 @Override public List<DocumentNode> findHierarchy(UUID v){return jdbc.sql("SELECT * FROM document_nodes WHERE material_version_id=:v ORDER BY ordinal NULLS FIRST,id").param("v",v).query((r,n)->new DocumentNode(r.getObject("id",UUID.class),r.getObject("material_version_id",UUID.class),r.getObject("parent_id",UUID.class),DocumentNodeType.valueOf(r.getString("node_type")),r.getString("title"),r.getObject("ordinal",Integer.class),r.getObject("start_page",Integer.class),r.getObject("end_page",Integer.class),r.getObject("start_offset",Long.class),r.getObject("end_offset",Long.class),DocumentNodeDetectionOrigin.valueOf(r.getString("detection_origin")),r.getString("detection_confidence"),r.getTimestamp("created_at").toInstant())).list();}
 @Override public List<TextBlock> findByPhysicalPage(UUID v,int first,int last){if(first<1||last<first)throw new IllegalArgumentException("Invalid page range");return jdbc.sql("""
SELECT * FROM text_blocks WHERE material_version_id=:v AND page_number BETWEEN :first AND :last AND block_type IN ('PAGE_TEXT','TABLE_TEXT') ORDER BY page_number,CASE block_type WHEN 'PAGE_TEXT' THEN 0 ELSE 1 END,ordinal
""").param("v",v).param("first",first).param("last",last).query((r,n)->new TextBlock(r.getObject("id",UUID.class),r.getObject("material_version_id",UUID.class),r.getObject("document_node_id",UUID.class),r.getObject("page_number",Integer.class),TextBlockType.valueOf(r.getString("block_type")),r.getInt("ordinal"),r.getString("content"),TextBlockExtractionMethod.valueOf(r.getString("extraction_method")),r.getString("quality")==null?null:TextBlockQuality.valueOf(r.getString("quality")),r.getTimestamp("created_at").toInstant(),r.getString("normalized_content"))).list();}
 @Override public List<VisualSource> findVisualsByPhysicalPage(UUID v,int first,int last){return jdbc.sql("SELECT id,material_version_id,document_node_id,page_number FROM visual_assets WHERE material_version_id=:v AND page_number BETWEEN :first AND :last ORDER BY page_number,id").param("v",v).param("first",first).param("last",last).query((r,n)->new VisualSource(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),r.getInt(4))).list();}
 @Override public void persistOrVerify(UUID v,List<ChunkDraft> drafts){requireTx();lock(v);for(ChunkDraft d:drafts){if(!v.equals(d.materialVersionId())||!ChunkIdentity.forChunk(v,d.chunkIndex()).equals(d.id()))throw new IllegalStateException("Invalid deterministic chunk identity");verifySources(v,d);String path=writeJson(d.headingPath());
   int inserted=jdbc.sql("""
INSERT INTO chunks(id,material_version_id,document_node_id,chunk_index,content,token_count,page_start,page_end,heading_path,content_type,extraction_method,quality,source_order,is_active,created_at) VALUES(:id,:v,:node,:idx,:content,:tokens,:start,:end,CAST(:path AS jsonb),:type,:method,:quality,:ord,true,:created) ON CONFLICT DO NOTHING
""").param("id",d.id()).param("v",v).param("node",d.documentNodeId()).param("idx",d.chunkIndex()).param("content",d.content()).param("tokens",d.tokenCount()).param("start",d.pageStart()).param("end",d.pageEnd()).param("path",path).param("type",d.contentType().name()).param("method",d.extractionMethod().name()).param("quality",d.quality()==null?null:d.quality().name()).param("ord",d.sourceOrder()).param("created",Timestamp.from(Instant.now())).update();
   if(inserted==0)verifyChunk(d,path);for(var l:d.sourceLinks()){int x=jdbc.sql("INSERT INTO chunk_text_block_links(chunk_id,text_block_id,material_version_id,source_position,is_overlap) VALUES(:c,:b,:v,:p,:o) ON CONFLICT DO NOTHING").param("c",d.id()).param("b",l.textBlockId()).param("v",v).param("p",l.sourcePosition()).param("o",l.overlap()).update();if(x==0&&!linkMatches(d.id(),l))throw new IllegalStateException("Chunk source link conflicts");}for(UUID visual:d.visualAssetIds()){int x=jdbc.sql("INSERT INTO chunk_visual_links VALUES(:c,:a,:v,'NEARBY') ON CONFLICT DO NOTHING").param("c",d.id()).param("a",visual).param("v",v).update();if(x==0&&!visualMatches(d.id(),visual))throw new IllegalStateException("Chunk visual link conflicts");}}
 }
 private void verifySources(UUID v,ChunkDraft d){for(var l:d.sourceLinks()){Integer ok=jdbc.sql("""
SELECT count(*) FROM text_blocks tb JOIN document_nodes dn ON dn.id=tb.document_node_id AND dn.material_version_id=tb.material_version_id WHERE tb.id=:id AND tb.material_version_id=:v AND tb.normalized_content IS NOT NULL AND tb.document_node_id=:node AND tb.page_number BETWEEN dn.start_page AND dn.end_page AND tb.block_type IN ('PAGE_TEXT','TABLE_TEXT') AND (tb.block_type<>'TABLE_TEXT' OR tb.content=tb.normalized_content)
""").param("id",l.textBlockId()).param("v",v).param("node",d.documentNodeId()).query(Integer.class).single();if(ok!=1)throw new IllegalStateException("Chunk source provenance is invalid");}}
 private void verifyChunk(ChunkDraft d,String path){Integer n=jdbc.sql("""
SELECT count(*) FROM chunks WHERE id=:id AND material_version_id=:v AND chunk_index=:idx AND document_node_id=:node AND content=:content AND token_count=:tokens AND page_start=:start AND page_end=:end AND heading_path=CAST(:path AS jsonb) AND content_type=:type AND extraction_method=:method AND quality IS NOT DISTINCT FROM :quality AND source_order=:ord AND is_active
""").param("id",d.id()).param("v",d.materialVersionId()).param("idx",d.chunkIndex()).param("node",d.documentNodeId()).param("content",d.content()).param("tokens",d.tokenCount()).param("start",d.pageStart()).param("end",d.pageEnd()).param("path",path).param("type",d.contentType().name()).param("method",d.extractionMethod().name()).param("quality",d.quality()==null?null:d.quality().name()).param("ord",d.sourceOrder()).query(Integer.class).single();if(n!=1)throw new IllegalStateException("Durable chunk conflicts with deterministic output");}
 private boolean linkMatches(UUID c,ChunkDraft.SourceLink l){return jdbc.sql("SELECT count(*) FROM chunk_text_block_links WHERE chunk_id=:c AND source_position=:p AND text_block_id=:b AND is_overlap=:o").param("c",c).param("p",l.sourcePosition()).param("b",l.textBlockId()).param("o",l.overlap()).query(Integer.class).single()==1;}
 private boolean visualMatches(UUID c,UUID a){return jdbc.sql("SELECT count(*) FROM chunk_visual_links WHERE chunk_id=:c AND visual_asset_id=:a AND relationship_type='NEARBY'").param("c",c).param("a",a).query(Integer.class).single()==1;}
 @Override public void finalizeChunking(UUID v,int pages,List<ChunkDraft> expected){requireTx();if(lock(v)!=pages)throw new IllegalStateException("Material page count changed during chunking");Integer count=jdbc.sql("SELECT count(*) FROM chunks WHERE material_version_id=:v").param("v",v).query(Integer.class).single();if(count!=expected.size())throw new IllegalStateException("Durable chunk count conflicts");for(ChunkDraft d:expected){verifyChunk(d,writeJson(d.headingPath()));Integer links=jdbc.sql("SELECT count(*) FROM chunk_text_block_links WHERE chunk_id=:id").param("id",d.id()).query(Integer.class).single();Integer visuals=jdbc.sql("SELECT count(*) FROM chunk_visual_links WHERE chunk_id=:id").param("id",d.id()).query(Integer.class).single();if(links!=d.sourceLinks().size()||visuals!=d.visualAssetIds().size())throw new IllegalStateException("Durable chunk links conflict");for(var l:d.sourceLinks())if(!linkMatches(d.id(),l))throw new IllegalStateException("Durable source links conflict");for(UUID a:d.visualAssetIds())if(!visualMatches(d.id(),a))throw new IllegalStateException("Durable visual links conflict");}
   Integer invalid=jdbc.sql("""
SELECT count(*) FROM chunks c WHERE c.material_version_id=:v AND (c.chunk_index<1 OR c.content='' OR c.token_count IS NULL OR c.token_count<1 OR c.token_count>1000 OR c.page_start<1 OR c.page_end<c.page_start OR NOT c.is_active OR NOT EXISTS(SELECT 1 FROM chunk_text_block_links l WHERE l.chunk_id=c.id))
""").param("v",v).query(Integer.class).single();if(invalid!=0)throw new IllegalStateException("Durable chunk state is invalid");}
 private int lock(UUID v){return jdbc.sql(ELIGIBLE+" FOR UPDATE OF mv FOR SHARE OF m").param("version",v).query(Integer.class).optional().orElseThrow(()->new IllegalStateException("Material version is not eligible for chunking"));}
 private String writeJson(Object o){try{return json.writeValueAsString(o);}catch(JacksonException e){throw new IllegalStateException("Heading path serialization failed",e);}}
 private static void requireTx(){if(!TransactionSynchronizationManager.isActualTransactionActive())throw new IllegalStateException("Chunk persistence requires a transaction");}
}
