spring:
  config:
    activate:
      on-profile: pilot

hippocampus:
  security:
    cors:
      allowed-origins: ${HIPPOCAMPUS_CORS_ALLOWED_ORIGINS}

server:
  address: 0.0.0.0
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: true
        same-site: none

logging:
  structured:
    ecs:
      service:
        environment: pilot
